### ISSUE TITLE
Missing underscore dependency in package.json

### ISSUE THREAD

**Issue by moul** [juliangiuca/whoisjs#2]
I tried to use whoisjs on a fresh linux install, and had to npm install underscore manually.

You should consider to add `"underscore": "1.4.2"` to the dependencies section in your package.json

Cheers

**Comment by localtoast** [comment]
Thanks for filing the bug - I'll fix this and get it up into the NPM repo shortly.

Thanks again!

**Comment by localtoast** [comment]
I've updated package.json, accepted your pull request, and published 0.0.5 to npm.

Thanks for your help!
